run:
  timeout: 5m

  skip-dirs:
    - external

linters:
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - asciicheck
    - bidichk
    - bodyclose
    - cyclop
    - errorlint
    - funlen
    - goconst
    - goimports
    - gosec
    - noctx
    - prealloc
    - predeclared
    - revive
    - unconvert

linters-settings:
  cyclop:
    # The maximal code complexity to report.
    # Default: 10
    max-complexity: 15
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 100
