basePath: /api
definitions:
  ctx.IDList:
    properties:
      ids:
        items:
          type: integer
        type: array
    required:
    - ids
    type: object
  ctx.Response:
    properties:
      count:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  db.BillDetails:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        description: income(收入) pay(支出)
        type: string
      ledger:
        type: string
      money:
        type: number
      name:
        type: string
      note:
        type: string
      type:
        type: string
    type: object
  db.BillTemplate:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        description: type(分类) ledger(账本)
        type: string
      name:
        type: string
      note:
        type: string
      times:
        type: integer
    type: object
  details.base:
    properties:
      key:
        type: string
      value:
        type: number
    type: object
  details.createParam:
    properties:
      created_at:
        type: string
      kind:
        enum:
        - income
        - pay
        type: string
      ledger:
        maxLength: 20
        type: string
      money:
        type: number
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
      type:
        maxLength: 20
        type: string
    required:
    - money
    type: object
  details.updateParam:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        enum:
        - income
        - pay
        type: string
      ledger:
        maxLength: 20
        type: string
      money:
        type: number
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
      type:
        maxLength: 20
        type: string
    required:
    - id
    - money
    type: object
  template.createParam:
    properties:
      created_at:
        type: string
      kind:
        description: type(分类) ledger(账本)
        enum:
        - type
        - ledger
        type: string
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - kind
    - name
    type: object
  template.updateParam:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        description: type(分类) ledger(账本)
        enum:
        - type
        - ledger
        type: string
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - id
    - kind
    - name
    type: object
info:
  contact: {}
  title: beyond api
paths:
  /bill/details:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除明细
      tags:
      - bill
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: kind
        in: query
        name: kind[]
        type: string
      - description: type
        in: query
        name: type[]
        type: string
      - description: ledger
        in: query
        name: ledger[]
        type: string
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.BillDetails'
                  type: array
              type: object
      summary: 查询明细
      tags:
      - bill
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/details.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillDetails'
              type: object
      summary: 增加明细
      tags:
      - bill
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/details.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillDetails'
              type: object
      summary: 更新明细
      tags:
      - bill
  /bill/details/chart/line:
    get:
      consumes:
      - application/json
      parameters:
      - description: date
        enum:
        - day
        - week
        - month
        - year
        in: query
        name: date
        required: true
        type: string
      - description: kind
        enum:
        - income
        - pay
        in: query
        name: kind
        type: string
      - description: type
        in: query
        name: type[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/details.base'
                  type: array
              type: object
      summary: 折线图
      tags:
      - bill
  /bill/details/chart/pie:
    get:
      consumes:
      - application/json
      parameters:
      - description: which field to aggregate
        enum:
        - name
        - type
        in: query
        name: field
        type: string
      - description: kind
        enum:
        - income
        - pay
        in: query
        name: kind
        type: string
      - description: created_at
        in: query
        name: created_at[]
        type: string
      - description: ledger
        in: query
        name: ledger[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/details.base'
                  type: array
              type: object
      summary: 饼图
      tags:
      - bill
  /bill/template:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除模板
      tags:
      - bill
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.BillTemplate'
                  type: array
              type: object
      summary: 模板列表
      tags:
      - bill
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/template.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillTemplate'
              type: object
      summary: 添加模板
      tags:
      - bill
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/template.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillTemplate'
              type: object
      summary: 更新模板
      tags:
      - bill
swagger: "2.0"
