basePath: /api
definitions:
  Type.createParam:
    properties:
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - name
    type: object
  Type.updateParam:
    properties:
      id:
        type: integer
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - id
    - name
    type: object
  ctx.IDList:
    properties:
      ids:
        items:
          type: integer
        type: array
    required:
    - ids
    type: object
  ctx.Response:
    properties:
      count:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  db.BillDetails:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        description: income(收入) pay(支出)
        type: string
      ledger:
        type: string
      money:
        type: number
      note:
        type: string
      type:
        type: string
    type: object
  db.BillLedger:
    properties:
      budget:
        type: number
      created_at:
        type: string
      id:
        type: integer
      is_default:
        type: boolean
      name:
        type: string
      note:
        type: string
      times:
        type: integer
    type: object
  db.BillType:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      note:
        type: string
      times:
        type: integer
    type: object
  db.Travel:
    properties:
      created_at:
        type: string
      id:
        type: integer
      level:
        description: Area.Level
        type: string
      name:
        description: Area.Name
        type: string
      note:
        type: string
    type: object
  details.base:
    properties:
      key:
        type: string
      value:
        type: number
    type: object
  details.createParam:
    properties:
      created_at:
        type: string
      kind:
        enum:
        - income
        - pay
        type: string
      ledger:
        maxLength: 20
        type: string
      money:
        type: number
      note:
        maxLength: 200
        type: string
      type:
        maxLength: 20
        type: string
    required:
    - money
    type: object
  details.lineResp:
    properties:
      bases:
        items:
          $ref: '#/definitions/details.base'
        type: array
      budget:
        type: number
    type: object
  details.updateParam:
    properties:
      created_at:
        type: string
      id:
        type: integer
      kind:
        enum:
        - income
        - pay
        type: string
      ledger:
        maxLength: 20
        type: string
      money:
        type: number
      note:
        maxLength: 200
        type: string
      type:
        maxLength: 20
        type: string
    required:
    - id
    - money
    type: object
  ledger.createParam:
    properties:
      budget:
        type: number
      is_default:
        type: boolean
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - name
    type: object
  ledger.updateParam:
    properties:
      budget:
        type: number
      id:
        type: integer
      is_default:
        type: boolean
      name:
        maxLength: 20
        type: string
      note:
        maxLength: 200
        type: string
    required:
    - id
    - name
    type: object
  travel.allListResp:
    properties:
      name:
        type: string
    type: object
  travel.createParam:
    properties:
      created_at:
        type: string
      name:
        type: string
      note:
        type: string
    required:
    - name
    type: object
  travel.updateParam:
    properties:
      created_at:
        type: string
      id:
        type: integer
      name:
        type: string
      note:
        type: string
    required:
    - id
    - name
    type: object
info:
  contact: {}
  title: beyond api
paths:
  /bill/details:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除明细
      tags:
      - bill
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: kind
        in: query
        name: kind[]
        type: string
      - description: type
        in: query
        name: type[]
        type: string
      - description: ledger
        in: query
        name: ledger[]
        type: string
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.BillDetails'
                  type: array
              type: object
      summary: 查询明细
      tags:
      - bill
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/details.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillDetails'
              type: object
      summary: 增加明细
      tags:
      - bill
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/details.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillDetails'
              type: object
      summary: 更新明细
      tags:
      - bill
  /bill/details/chart/line:
    get:
      consumes:
      - application/json
      parameters:
      - description: date
        enum:
        - day
        - week
        - month
        - year
        in: query
        name: date
        required: true
        type: string
      - description: kind
        enum:
        - income
        - pay
        in: query
        name: kind
        type: string
      - description: type
        in: query
        name: type[]
        type: string
      - description: ledger
        in: query
        name: ledger[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/details.lineResp'
              type: object
      summary: 折线图
      tags:
      - bill
  /bill/details/chart/pie:
    get:
      consumes:
      - application/json
      parameters:
      - description: which field to aggregate
        enum:
        - ledger
        - type
        in: query
        name: field
        type: string
      - description: kind
        enum:
        - income
        - pay
        in: query
        name: kind
        type: string
      - description: created_at
        in: query
        name: created_at[]
        type: string
      - description: ledger
        in: query
        name: ledger[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/details.base'
                  type: array
              type: object
      summary: 饼图
      tags:
      - bill
  /bill/ledger:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除账本
      tags:
      - bill
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.BillLedger'
                  type: array
              type: object
      summary: 账本列表
      tags:
      - bill
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ledger.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillLedger'
              type: object
      summary: 添加账本
      tags:
      - bill
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ledger.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillLedger'
              type: object
      summary: 更新账本
      tags:
      - bill
  /bill/type:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除分类
      tags:
      - bill
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.BillType'
                  type: array
              type: object
      summary: 分类列表
      tags:
      - bill
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Type.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillType'
              type: object
      summary: 添加分类
      tags:
      - bill
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/Type.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.BillType'
              type: object
      summary: 更新分类
      tags:
      - bill
  /travel:
    delete:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/ctx.IDList'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/ctx.Response'
      summary: 删除标记
      tags:
      - travel
    get:
      consumes:
      - application/json
      parameters:
      - description: page
        in: query
        name: page
        type: integer
      - description: size
        in: query
        name: size
        type: integer
      - description: id
        in: query
        name: id[]
        type: integer
      - description: created_at
        in: query
        name: created_at[]
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/db.Travel'
                  type: array
              type: object
      summary: 足迹
      tags:
      - travel
    post:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/travel.createParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.Travel'
              type: object
      summary: 标记地点
      tags:
      - travel
    put:
      consumes:
      - application/json
      parameters:
      - description: request payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/travel.updateParam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  $ref: '#/definitions/db.Travel'
              type: object
      summary: 更新标记
      tags:
      - travel
  /travel/all:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/ctx.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/travel.allListResp'
                  type: array
              type: object
      summary: 所有标记过的城市
      tags:
      - travel
swagger: "2.0"
