on:
  release:
    types: [created]

env:
  CI: false

jobs:
  releases-matrix:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64]
        exclude:
          - goarch: "386"
            goos: darwin
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18.5.0
      - run: cd ui && yarn install --registry https://registry.npm.taobao.org/ && yarn build

      - name: windows gui
        if: matrix.goos == 'windows'
        run: echo "LDFLAGS=-H=windowsgui" >> $GITHUB_ENV

      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "1.18"
          binary_name: "beyond"
          extra_files: config/config.yaml dist
          md5sum: false
          pre_command: "export CGO_ENABLED=0"
          build_flags: -trimpath -a
          ldflags: ${{ env.LDFLAGS }}
